import type { Post, PostType } from '@/types/domain';
import { communityId } from './communities';
import { eventId } from './events';
import { uid } from './ids';
import { mediaId } from './media';
import { profileId } from './profiles';
import { projectId } from './projects';
import { resourceId } from './resources';
import { topicId, type TopicSlug } from './topics';
import { whyStoryId } from './why';

/**
 * Ana akis seed verisi (PROJECT_SPEC 7.1).
 *
 * Kritik urun kurali: bu akis yalnizca proje/firsat icerigi olamaz. Mizah,
 * gundelik sohbet, soru, kisa video ve topluluk paylasimlari birinci sinif
 * icerik olarak ayni akista yasar (PROJECT_SPEC 1.1 madde 2).
 */

export const postId = (slug: string) => uid('post', slug);

interface PostInput {
  slug: string;
  author: string;
  type: PostType;
  body: string;
  community?: string;
  topics: TopicSlug[];
  provinceCode?: string | null;
  districtCode?: string | null;
  project?: string;
  event?: string;
  why?: string;
  resource?: string;
  media?: string[];
  /** Kisa video akisinda gorunecek dikey klip. */
  video?: { key: string; kind: NonNullable<Post['videoKind']> };
  hoursAgo: number;
  likes: number;
  comments: number;
  reposts?: number;
}

const POSTS: PostInput[] = [
  // --- Gundelik sohbet ve mizah -------------------------------------------
  {
    slug: 'kahve-derleyici',
    author: 'tolga.mizah',
    type: 'text',
    body: 'Üç saattir hata arıyorum. Sorun noktalı virgül değilmiş, ben yanlış klasördeki dosyayı derliyormuşum. Kendime kahve borçluyum.',
    community: 'robotik',
    topics: ['robotik'],
    provinceCode: '34',
    hoursAgo: 3,
    likes: 412,
    comments: 38,
    reposts: 22,
  },
  {
    slug: 'mizah-derleyici-video',
    author: 'tolga.mizah',
    type: 'video',
    body: 'Bugünün felaketi kısa versiyon. Sesi açmanıza gerek yok, yüz ifadem yeterli.',
    community: 'robotik',
    topics: ['robotik', 'oyun-gelistirme'],
    provinceCode: '34',
    video: { key: 'feed-mizah-derleyici', kind: 'gundelik' },
    hoursAgo: 9,
    likes: 903,
    comments: 74,
    reposts: 51,
  },
  {
    slug: 'lehim-kokusu',
    author: 'mert.kod',
    type: 'text',
    body: 'Lehim kokusu alınca "ah çocukluğum" diyen tek kişi ben miyim? Odada üç kişiyiz, ikisi pencereyi açtı.',
    community: 'robotik',
    topics: ['robotik'],
    provinceCode: '06',
    hoursAgo: 14,
    likes: 236,
    comments: 29,
  },
  {
    slug: 'sabah-lab',
    author: 'zeynep.bio',
    type: 'text',
    body: 'Laboratuvara sabah 7’de geldim çünkü santrifüj sırası yoktu. Şu an tek başımayım ve buzdolabının sesi beni rahatsız etmeye başladı.',
    community: 'biyoteknoloji',
    topics: ['biyoteknoloji'],
    provinceCode: '34',
    hoursAgo: 27,
    likes: 148,
    comments: 17,
  },
  {
    slug: 'jam-son-saat-video',
    author: 'selin.oyun',
    type: 'video',
    body: 'Jam’in son saati. Ses yok, menü yok, ama oyun çalışıyor. Bu da bir başarı sayılır.',
    community: 'game-jam-ege',
    topics: ['oyun-gelistirme'],
    provinceCode: '35',
    districtCode: '35-17',
    video: { key: 'feed-jam-son-saat', kind: 'gundelik' },
    hoursAgo: 20,
    likes: 318,
    comments: 41,
  },
  {
    slug: 'kirmizi-led',
    author: 'kaan.roket',
    type: 'text',
    body: 'Devrede tek bir kırmızı LED var ve gördüğüm en güzel şey. Uzaktan ateşleme devresi ilk denemede çalıştı.',
    community: 'izmir-havacilik',
    topics: ['havacilik-uzay'],
    provinceCode: '35',
    districtCode: '35-07',
    hoursAgo: 33,
    likes: 194,
    comments: 12,
  },
  {
    slug: 'klavye-tercihi',
    author: 'emre.guvenlik',
    type: 'text',
    body: 'Mekanik klavye tartışmasına girmeyeceğim ama girsem kazanırdım.',
    community: 'siber-guvenlik',
    topics: ['siber-guvenlik'],
    provinceCode: '34',
    hoursAgo: 52,
    likes: 521,
    comments: 88,
    reposts: 19,
  },
  {
    slug: 'gece-gokyuzu-foto',
    author: 'ece.uzay',
    type: 'image',
    body: 'Dün gece Karaburun’dan. Şehirden bir saat uzaklaşmak bu kadar fark ediyor.',
    community: 'gece-gokyuzu',
    topics: ['havacilik-uzay'],
    media: ['img-gozlem-gecesi'],
    hoursAgo: 40,
    likes: 687,
    comments: 45,
    reposts: 31,
  },
  {
    slug: 'ilk-gonderi-cekingen',
    author: 'irem.lise',
    type: 'text',
    body: 'Buraya ilk kez yazıyorum, biraz çekiniyorum. Lise sonum ve biyoteknoloji okumak istiyorum. Üniversitede ilk yıl neye çalışmalıyım?',
    community: 'lise-biyoteknoloji',
    topics: ['biyoteknoloji'],
    provinceCode: '35',
    districtCode: '35-25',
    hoursAgo: 5,
    likes: 96,
    comments: 34,
  },

  // --- Sorular ------------------------------------------------------------
  {
    slug: 'soru-anten-yerlesimi',
    author: 'onur.enerji',
    type: 'question',
    body: 'LoRa düğümlerinde anteni dikey mi yatay mı konumlandırmalı? Serada iki farklı sonuç aldım ve nedenini çözemedim. Deneyimi olan var mı?',
    community: 'surdurulebilirlik',
    topics: ['surdurulebilirlik', 'robotik'],
    provinceCode: '35',
    districtCode: '35-25',
    project: 'sera-sensor-agi',
    hoursAgo: 11,
    likes: 74,
    comments: 26,
  },
  {
    slug: 'soru-ekran-okuyucu-form',
    author: 'nazli.tasarim',
    type: 'video',
    body: 'Bu formda hata mesajını hangi alana bağlamam gerektiğini çözemedim. Ekran okuyucu kullanan biri 2 dakika ayırabilir mi?',
    community: 'erisilebilir-arayuz',
    topics: ['tasarim-urun'],
    provinceCode: '35',
    districtCode: '35-21',
    video: { key: 'feed-ekran-okuyucu-soru', kind: 'soru' },
    hoursAgo: 16,
    likes: 143,
    comments: 22,
  },
  {
    slug: 'soru-ilk-ctf',
    author: 'irem.lise',
    type: 'question',
    body: 'CTF’e başlamak istiyorum ama nereden başlayacağımı bilmiyorum. Yasal olarak pratik yapabileceğim yerler neresi?',
    community: 'ctf-baslangic',
    topics: ['siber-guvenlik'],
    provinceCode: '35',
    hoursAgo: 62,
    likes: 58,
    comments: 19,
  },
  {
    slug: 'soru-simulasyon-fark',
    author: 'mert.kod',
    type: 'question',
    body: 'Simülasyonda %95, pistte %60. Aynı modeli kullananlar bu farkı nasıl kapattı? Veri artırma dışında ne işe yaradı?',
    community: 'otonom-arac-takimlari',
    topics: ['robotik', 'yapay-zeka'],
    provinceCode: '06',
    project: 'otonom-simulasyon',
    hoursAgo: 44,
    likes: 167,
    comments: 43,
  },
  {
    slug: 'soru-makale-secimi',
    author: 'irem.lise',
    type: 'question',
    body: 'Lise seviyesinde okunabilecek biyoteknoloji makalesi önerisi var mı? Çoğu çok ağır geliyor ve yarısında bırakıyorum.',
    community: 'lise-biyoteknoloji',
    topics: ['biyoteknoloji'],
    provinceCode: '35',
    hoursAgo: 88,
    likes: 112,
    comments: 27,
  },
  {
    slug: 'soru-pil-omru',
    author: 'kaan.roket',
    type: 'question',
    body: 'Saha uçuşlarında telemetri kaydını hangi aralıkla alıyorsunuz? 1 Hz yetiyor mu yoksa iniş anını kaçırır mıyım?',
    community: 'izmir-havacilik',
    topics: ['havacilik-uzay'],
    provinceCode: '35',
    districtCode: '35-07',
    hoursAgo: 100,
    likes: 63,
    comments: 15,
  },

  // --- Proje guncellemeleri -----------------------------------------------
  {
    slug: 'ruzgar-cati-kurulum',
    author: 'baran.demo',
    type: 'project_update',
    body: 'Konak’ta ilk çatı kurulumu tamam. Üç haftadır kesintisiz veri geliyor. En büyük sürprizi öğleden sonra saatlerindeki ani düşüşler yaptı, sebebini hâlâ tartışıyoruz.',
    community: 'surdurulebilirlik',
    topics: ['surdurulebilirlik', 'robotik'],
    provinceCode: '35',
    districtCode: '35-21',
    project: 'ruzgar-olcer',
    media: ['img-ruzgar-olcer-cati'],
    hoursAgo: 30,
    likes: 289,
    comments: 33,
    reposts: 14,
  },
  {
    slug: 'ruzgar-tunel-video',
    author: 'baran.demo',
    type: 'video',
    body: 'Rüzgâr tünelinde kalibrasyon. 3-18 m/s aralığında %4 sapma. Kalibrasyon tablosunu depoya koydum.',
    community: 'surdurulebilirlik',
    topics: ['surdurulebilirlik'],
    provinceCode: '35',
    districtCode: '35-21',
    project: 'ruzgar-olcer',
    video: { key: 'feed-tunel-testi', kind: 'demo' },
    hoursAgo: 54,
    likes: 341,
    comments: 28,
  },
  {
    slug: 'roket-ilk-atesleme-video',
    author: 'kaan.roket',
    type: 'video',
    body: 'Standda ilk gerçek ateşleme. Muhafaza sağlam, uzaktan tetikleme sorunsuz. Eğri katalogdan %11 düşük çıktı ve bu tam da aradığımız cevaptı.',
    community: 'izmir-havacilik',
    topics: ['havacilik-uzay'],
    provinceCode: '35',
    districtCode: '35-07',
    project: 'model-roket-itki',
    video: { key: 'feed-roket-ateşleme', kind: 'demo' },
    hoursAgo: 26,
    likes: 476,
    comments: 52,
    reposts: 27,
  },
  {
    slug: 'itki-egrisi-paylasim',
    author: 'kaan.roket',
    type: 'project_update',
    body: 'İlk ölçtüğümüz itki eğrisi. Katalog değeriyle farkı görünce takımda kimse bir şey söyleyemedi. Ham veriyi topluluk arşivine koyduk.',
    community: 'izmir-havacilik',
    topics: ['havacilik-uzay'],
    provinceCode: '35',
    districtCode: '35-07',
    project: 'model-roket-itki',
    media: ['img-itki-egrisi'],
    hoursAgo: 78,
    likes: 318,
    comments: 24,
  },
  {
    slug: 'sera-dugum-bozuldu',
    author: 'onur.enerji',
    type: 'project_update',
    body: 'Seradaki altı düğümden biri nem yüzünden bozuldu. Kutu tasarımını değiştiriyoruz. Başarısızlığı da yazıyorum çünkü bu bilgi bir sonrakine lazım olacak.',
    community: 'surdurulebilirlik',
    topics: ['surdurulebilirlik'],
    provinceCode: '35',
    districtCode: '35-25',
    project: 'sera-sensor-agi',
    media: ['img-sera-dugum'],
    hoursAgo: 48,
    likes: 224,
    comments: 31,
  },
  {
    slug: 'sera-ilerleme-video',
    author: 'onur.enerji',
    type: 'video',
    body: 'Altı düğüm, altı hafta. Kısa saha turu.',
    community: 'surdurulebilirlik',
    topics: ['surdurulebilirlik'],
    provinceCode: '35',
    districtCode: '35-25',
    project: 'sera-sensor-agi',
    video: { key: 'feed-sensor-ilerleme', kind: 'ilerleme' },
    hoursAgo: 70,
    likes: 176,
    comments: 14,
  },
  {
    slug: 'oyun-menu-test',
    author: 'selin.oyun',
    type: 'project_update',
    body: 'İlk dış test sonucu: 4 kullanıcıdan 3’ü menüyü yardımsız tamamladı. Takılan kişi tuş atama ekranında kayboldu, orayı baştan tasarlıyoruz.',
    community: 'erisilebilir-arayuz',
    topics: ['oyun-gelistirme', 'tasarim-urun'],
    provinceCode: '35',
    districtCode: '35-17',
    project: 'erisilebilir-oyun-menusu',
    media: ['img-oyun-menu'],
    hoursAgo: 36,
    likes: 208,
    comments: 26,
  },
  {
    slug: 'lab-gunlugu-filtre',
    author: 'zeynep.bio',
    type: 'project_update',
    body: 'Açık Laboratuvar Günlüğü’nde en çok kullanılan filtrenin "başarısız" etiketi olduğunu gördüm. Bu proje için aldığım en iyi geri bildirim bu.',
    community: 'biyoteknoloji',
    topics: ['biyoteknoloji'],
    provinceCode: '34',
    project: 'laboratuvar-gunlugu',
    media: ['img-lab-defteri'],
    hoursAgo: 92,
    likes: 394,
    comments: 37,
    reposts: 18,
  },
  {
    slug: 'otonom-yagmur-senaryo',
    author: 'mert.kod',
    type: 'project_update',
    body: 'Yağmur ve gece senaryolarını ekledik, model başarımı %22 düştü. Bu kötü bir haber değil: simülasyon nihayet gerçeğe benzemeye başladı.',
    community: 'otonom-arac-takimlari',
    topics: ['robotik', 'yapay-zeka'],
    provinceCode: '06',
    project: 'otonom-simulasyon',
    media: ['img-otonom-sahne'],
    hoursAgo: 58,
    likes: 267,
    comments: 34,
  },
  {
    slug: 'iha-saha-testi-yaklasiyor',
    author: 'burak.uav',
    type: 'project_update',
    body: 'Rüzgârlı havada ilk saha testi bu hafta. Simülasyonda %88 tanıma var ama gerçek pistin ne diyeceğini merak ediyorum.',
    community: 'havacilik-uzay',
    topics: ['havacilik-uzay', 'yapay-zeka'],
    provinceCode: '06',
    project: 'iha-inis-yardimcisi',
    hoursAgo: 21,
    likes: 183,
    comments: 19,
  },
  {
    slug: 'ozetleme-forum-alani',
    author: 'ayse.veri',
    type: 'project_update',
    body: 'Değerlendirme setine forum metinleri alanını ekledik: 300 metin, 900 insan özeti. Forum dili haber dilinden çok daha zor çıktı.',
    community: 'turkce-nlp',
    topics: ['yapay-zeka'],
    provinceCode: '34',
    project: 'turkce-ozetleme-seti',
    hoursAgo: 66,
    likes: 312,
    comments: 29,
    reposts: 16,
  },
  {
    slug: 'ctf-moderator-onay',
    author: 'emre.guvenlik',
    type: 'project_update',
    body: 'Yol haritası moderatör doğrulaması aldı. 12 modülün tamamı izinli platformlarda çalışacak şekilde yeniden kontrol edildi.',
    community: 'ctf-baslangic',
    topics: ['siber-guvenlik'],
    provinceCode: '34',
    project: 'ctf-yol-haritasi',
    media: ['img-ctf-tahta'],
    hoursAgo: 108,
    likes: 246,
    comments: 21,
  },

  // --- Etkinlik duyurulari ------------------------------------------------
  {
    slug: 'duyuru-roket-atolyesi',
    author: 'kaan.roket',
    type: 'event_announcement',
    body: 'İzmir Model Roket Atölyesi için kayıtlar açıldı. Malzeme bizden, deneyim gerekmiyor. Kontenjan 24 kişi.',
    community: 'izmir-havacilik',
    topics: ['havacilik-uzay'],
    provinceCode: '35',
    districtCode: '35-07',
    event: 'izmir-model-roket-atolyesi',
    hoursAgo: 18,
    likes: 158,
    comments: 23,
    reposts: 12,
  },
  {
    slug: 'duyuru-demo-gunu',
    author: 'egeteknopark.demo',
    type: 'event_announcement',
    body: 'Demo Günü başvuruları açık. Jüri yok, 5 dakika sunum ve gerçek geri bildirim var. Erken aşama takımlar öncelikli.',
    topics: ['tasarim-urun', 'yapay-zeka'],
    provinceCode: '35',
    districtCode: '35-07',
    event: 'ege-teknopark-demo-gunu',
    hoursAgo: 25,
    likes: 271,
    comments: 18,
    reposts: 24,
  },
  {
    slug: 'duyuru-iha-saha',
    author: 'elif.demo',
    type: 'event_announcement',
    body: 'İHA saha uçuşu ve telemetri günü için tarih netleşti. İzleyici olarak da gelebilirsiniz, uçurmak zorunda değilsiniz.',
    community: 'izmir-havacilik',
    topics: ['havacilik-uzay'],
    provinceCode: '35',
    districtCode: '35-23',
    event: 'izmir-iha-saha-ucusu',
    hoursAgo: 34,
    likes: 132,
    comments: 11,
  },
  {
    slug: 'duyuru-erisilebilirlik-denetimi',
    author: 'nazli.tasarim',
    type: 'event_announcement',
    body: 'Bu ayki birlikte denetim gecesinde bir kamu hizmeti arayüzüne bakacağız. Çevrim içi katılım da var, ekran paylaşımıyla ilerliyoruz.',
    community: 'erisilebilir-arayuz',
    topics: ['tasarim-urun'],
    provinceCode: '35',
    districtCode: '35-21',
    event: 'izmir-erisilebilirlik-denetimi',
    hoursAgo: 42,
    likes: 189,
    comments: 16,
  },
  {
    slug: 'duyuru-ges-gezi',
    author: 'onur.enerji',
    type: 'event_announcement',
    body: 'Urla’daki kooperatif çatısını gezeceğiz. Ölçüm verilerini yerinde göstereceğiz, panel altına da gireceğiz.',
    community: 'ege-gunes-enerjisi',
    topics: ['surdurulebilirlik'],
    provinceCode: '35',
    districtCode: '35-30',
    event: 'ege-ges-saha-gezisi',
    media: ['img-panel-cati'],
    hoursAgo: 72,
    likes: 141,
    comments: 9,
  },
  {
    slug: 'duyuru-nlp-okuma',
    author: 'ayse.veri',
    type: 'event_announcement',
    body: 'Bu ayın okuma grubu makalesi belli oldu: morfolojik ayrıştırmanın özetleme başarımına etkisi. Çevrim içi, kayıt gerekmiyor.',
    community: 'turkce-nlp',
    topics: ['yapay-zeka'],
    event: 'turkce-nlp-okuma-grubu',
    hoursAgo: 13,
    likes: 205,
    comments: 14,
  },
  {
    slug: 'duyuru-lab-turu',
    author: 'biyolab.demo',
    type: 'event_announcement',
    body: 'Lise öğrencileri için laboratuvar turu. Kontenjan sınırlı, öğretmen eşliğinde grup başvurusu da alıyoruz.',
    topics: ['biyoteknoloji'],
    provinceCode: '34',
    event: 'istanbul-biyo-lab-turu',
    hoursAgo: 50,
    likes: 178,
    comments: 22,
  },
  {
    slug: 'duyuru-game-jam',
    author: 'selin.oyun',
    type: 'event_announcement',
    body: 'Game Jam Ege 48 saat için takım eşleştirme formu açıldı. Yalnız gelenler için endişelenmeyin, kimse takımsız kalmıyor.',
    community: 'game-jam-ege',
    topics: ['oyun-gelistirme'],
    provinceCode: '35',
    districtCode: '35-17',
    event: 'game-jam-ege-48',
    hoursAgo: 84,
    likes: 224,
    comments: 31,
    reposts: 17,
  },

  // --- Kaynak onerileri ---------------------------------------------------
  {
    slug: 'kaynak-makale-okuma',
    author: 'zeynep.bio',
    type: 'resource_suggestion',
    body: 'Makale okumaya yeni başlayanlar için yazdığım sırayı topluluk kaynaklarına ekledim. En çok işe yarayan madde: sınırlılıklar bölümünü atlamayın.',
    community: 'biyoteknoloji',
    topics: ['biyoteknoloji'],
    provinceCode: '34',
    resource: 'akademik-makale-okuma',
    hoursAgo: 45,
    likes: 267,
    comments: 18,
    reposts: 21,
  },
  {
    slug: 'kaynak-klavye-test',
    author: 'nazli.tasarim',
    type: 'resource_suggestion',
    body: '15 dakikalık klavye testi kontrol listesi. Fareyi bırakıp Tab’a basmak çoğu erişilebilirlik hatasını ilk turda gösteriyor.',
    community: 'erisilebilir-arayuz',
    topics: ['tasarim-urun'],
    provinceCode: '35',
    districtCode: '35-21',
    resource: 'klavye-ile-test',
    hoursAgo: 60,
    likes: 331,
    comments: 25,
    reposts: 29,
  },
  {
    slug: 'kaynak-lehim-video',
    author: 'mert.kod',
    type: 'video',
    body: '30 saniyede temiz lehim. Teli ucun üstüne değdirenler, bu size.',
    community: 'robotik',
    topics: ['robotik'],
    provinceCode: '06',
    video: { key: 'feed-lehim-nasil', kind: 'nasil' },
    hoursAgo: 38,
    likes: 512,
    comments: 44,
    reposts: 33,
  },
  {
    slug: 'kaynak-guvenli-yazilim',
    author: 'emre.guvenlik',
    type: 'resource_suggestion',
    body: 'Küçük projeler için güvenli yazılım kontrol listesi. En sık gördüğüm hata: yetki kontrolünün sadece arayüzde yapılması.',
    community: 'siber-guvenlik',
    topics: ['siber-guvenlik'],
    provinceCode: '34',
    resource: 'guvenli-yazilim-kontrol',
    hoursAgo: 96,
    likes: 288,
    comments: 22,
  },
  {
    slug: 'kaynak-ges-kontrol',
    author: 'onur.enerji',
    type: 'resource_suggestion',
    body: 'Çatı GES öncesi 8 kontrol maddesi. Statik rapor olmadan panele başlayan çok fazla insan görüyorum.',
    community: 'ege-gunes-enerjisi',
    topics: ['surdurulebilirlik'],
    provinceCode: '35',
    districtCode: '35-30',
    resource: 'ges-oncesi-kontrol',
    hoursAgo: 112,
    likes: 154,
    comments: 12,
  },
  {
    slug: 'kaynak-teleskop-video',
    author: 'ece.uzay',
    type: 'video',
    body: 'Teleskop kurulumu 40 saniyede. Kutup hizalamasını atlarsanız bütün gece takip kayar, tecrübeyle sabittir.',
    community: 'gece-gokyuzu',
    topics: ['havacilik-uzay'],
    video: { key: 'feed-teleskop-kurulum', kind: 'nasil' },
    hoursAgo: 76,
    likes: 398,
    comments: 27,
    reposts: 24,
  },
  {
    slug: 'kaynak-postmortem',
    author: 'selin.oyun',
    type: 'resource_suggestion',
    body: 'Jam sonrası post-mortem şablonu. Jam biter bitmez doldurun, bir hafta sonra hiçbir şey hatırlamıyorsunuz.',
    community: 'game-jam-ege',
    topics: ['oyun-gelistirme'],
    provinceCode: '35',
    districtCode: '35-17',
    resource: 'jam-postmortem',
    hoursAgo: 120,
    likes: 176,
    comments: 15,
  },

  // --- Neden hikayesi baglantilari ----------------------------------------
  {
    slug: 'neden-ruzgar-paylasim',
    author: 'baran.demo',
    type: 'why_link',
    body: 'Bu projeye neden başladığımı anlattım. Kısa versiyonu: bir soruya "bilmiyorum" demek zorunda kalmak.',
    topics: ['surdurulebilirlik'],
    provinceCode: '35',
    districtCode: '35-21',
    why: 'ruzgar-olcer-nedeni',
    project: 'ruzgar-olcer',
    hoursAgo: 12,
    likes: 452,
    comments: 39,
    reposts: 28,
  },
  {
    slug: 'neden-basarisiz-deney',
    author: 'zeynep.bio',
    type: 'why_link',
    body: 'Üç ayımı geri istemiyorum, sadece kimse aynı şeyi kaybetmesin. Neden panosuna yazdım.',
    topics: ['biyoteknoloji'],
    provinceCode: '34',
    why: 'basarisiz-deney-arsivi',
    project: 'laboratuvar-gunlugu',
    hoursAgo: 28,
    likes: 621,
    comments: 58,
    reposts: 44,
  },
  {
    slug: 'neden-oyun-menu',
    author: 'selin.oyun',
    type: 'why_link',
    body: 'Yaptığımız oyunu oynayamayan ilk kişi arkadaşımın kardeşiydi. O gün bugündür menüden başlıyorum.',
    topics: ['oyun-gelistirme', 'tasarim-urun'],
    provinceCode: '35',
    districtCode: '35-17',
    why: 'arkadasimin-kardesi',
    project: 'erisilebilir-oyun-menusu',
    hoursAgo: 19,
    likes: 508,
    comments: 47,
    reposts: 36,
  },
  {
    slug: 'neden-kirk-saniye',
    author: 'burak.uav',
    type: 'why_link',
    body: 'GPS’in kaybolduğu kırk saniyeyi yazdım. O geceden sonra tek sinyale güvenmiyorum.',
    topics: ['havacilik-uzay'],
    provinceCode: '06',
    why: 'kirk-saniye',
    project: 'iha-inis-yardimcisi',
    hoursAgo: 41,
    likes: 377,
    comments: 33,
  },
  {
    slug: 'neden-ekran-okuyucu',
    author: 'nazli.tasarim',
    type: 'why_link',
    body: 'Kendi tasarladığım formu ekran okuyucuyla dolduramadığım günü anlattım. Utanmadım, şaşırdım.',
    topics: ['tasarim-urun'],
    provinceCode: '35',
    districtCode: '35-21',
    why: 'ekran-okuyucu-ilk-kez',
    hoursAgo: 38,
    likes: 445,
    comments: 41,
    reposts: 30,
  },

  // --- Topluluk ve gundelik karisik ---------------------------------------
  {
    slug: 'topluluk-hosgeldin',
    author: 'elif.demo',
    type: 'text',
    body: 'İzmir Havacılık Meraklıları’na bu hafta 30 kişi katılmış. Yeni gelenler, ilk sorunuzu sormaktan çekinmeyin, burada kimse "bunu bilmiyor musun" demiyor.',
    community: 'izmir-havacilik',
    topics: ['havacilik-uzay'],
    provinceCode: '35',
    districtCode: '35-07',
    hoursAgo: 7,
    likes: 217,
    comments: 24,
  },
  {
    slug: 'harita-kesif-notu',
    author: 'elif.demo',
    type: 'image',
    body: 'İzmir’de aynı hafta içinde üç farklı ilçede etkinlik varmış ve ikisinden haberim yoktu. Haritadan bakınca fark ettim.',
    topics: ['havacilik-uzay', 'tasarim-urun'],
    provinceCode: '35',
    districtCode: '35-07',
    media: ['img-harita-izmir'],
    hoursAgo: 15,
    likes: 163,
    comments: 18,
  },
  {
    slug: 'yeni-ses-tanisma',
    author: 'irem.lise',
    type: 'text',
    body: 'Ödemiş’ten yazıyorum. Buradan biyoteknolojiyle ilgilenen başka biri var mı? Okulda bu konuyu konuşabileceğim kimse yok.',
    community: 'lise-biyoteknoloji',
    topics: ['biyoteknoloji'],
    provinceCode: '35',
    districtCode: '35-25',
    hoursAgo: 23,
    likes: 88,
    comments: 29,
  },
  {
    slug: 'kurumsal-program',
    author: 'egeteknopark.demo',
    type: 'text',
    body: 'Bu dönem ofis saatlerimizi öğrenci takımlarına da açıyoruz. Randevu almadan gelebilirsiniz, sadece ne üzerinde çalıştığınızı anlatın.',
    topics: ['tasarim-urun', 'surdurulebilirlik'],
    provinceCode: '35',
    districtCode: '35-07',
    hoursAgo: 55,
    likes: 192,
    comments: 13,
  },
  {
    slug: 'anadolu-uzay-duyuru',
    author: 'anadoluuzay.demo',
    type: 'text',
    body: 'Kulüp arşivimizdeki 40 uçuş raporunu açık erişime taşıdık. Öğrenci takımları serbestçe kullanabilir, atıf yeterli.',
    topics: ['havacilik-uzay'],
    provinceCode: '06',
    hoursAgo: 68,
    likes: 356,
    comments: 26,
    reposts: 41,
  },
  {
    slug: 'kod-kultur-acik-kaynak',
    author: 'kodkultur.demo',
    type: 'text',
    body: 'Açık kaynak katkı gününde ilk kez katkı yapan 14 kişi vardı. En zor kısım kod değil, ilk pull request’i açmakmış.',
    topics: ['siber-guvenlik', 'oyun-gelistirme'],
    provinceCode: '35',
    districtCode: '35-21',
    hoursAgo: 80,
    likes: 264,
    comments: 22,
  },
  {
    slug: 'yesilcati-olcum',
    author: 'yesilcati.demo',
    type: 'text',
    body: 'Kooperatif çatısında ilk yıl üretim verilerini paylaşıyoruz. Tahminimizin %7 altında kaldık, sebebini gölgelenme analizinde bulduk.',
    topics: ['surdurulebilirlik'],
    provinceCode: '35',
    districtCode: '35-30',
    hoursAgo: 104,
    likes: 148,
    comments: 17,
  },
  {
    slug: 'ayse-veri-gundelik',
    author: 'ayse.veri',
    type: 'text',
    body: 'Grafik çizmeyi sevmiyorum ama iyi bir grafik, üç paragraf açıklamadan daha çok şey anlatıyor. İsteksizce kabul ediyorum.',
    community: 'yapay-zeka',
    topics: ['yapay-zeka', 'tasarim-urun'],
    provinceCode: '34',
    hoursAgo: 31,
    likes: 298,
    comments: 26,
  },
  {
    slug: 'emre-ctf-hatirlatma',
    author: 'emre.guvenlik',
    type: 'text',
    body: 'Hatırlatma: öğrendiğiniz hiçbir şeyi izinsiz sistemde denemeyin. CTF ortamı bunun için var ve orada canınız istediği kadar kırın.',
    community: 'ctf-baslangic',
    topics: ['siber-guvenlik'],
    provinceCode: '34',
    hoursAgo: 47,
    likes: 431,
    comments: 19,
    reposts: 37,
  },
  {
    slug: 'burak-otopilot-not',
    author: 'burak.uav',
    type: 'text',
    body: 'Otopilot ayarlarını değiştirdiğinizde neyi neden değiştirdiğinizi yazın. Üç ay sonraki siz, bugünkü sizden nefret edecek.',
    community: 'havacilik-uzay',
    topics: ['havacilik-uzay'],
    provinceCode: '06',
    hoursAgo: 90,
    likes: 372,
    comments: 28,
    reposts: 25,
  },
  {
    slug: 'ece-veri-yedegi',
    author: 'ece.uzay',
    type: 'text',
    body: 'Gözlem gecesinin sonunda 42 GB ham veri var ve hiçbirini yedeklemedim. Bunu yazıyorum ki utançtan yedekleyeyim.',
    community: 'gece-gokyuzu',
    topics: ['havacilik-uzay'],
    hoursAgo: 36,
    likes: 254,
    comments: 31,
  },
  {
    slug: 'tolga-lise-tavsiye',
    author: 'tolga.mizah',
    type: 'text',
    body: 'Lise öğrencisi arkadaşlara: bu alanda hiçbirimiz her şeyi bilmiyoruz, sadece farklı şeylerde tıkanıyoruz. Sorun, gerçekten.',
    topics: ['robotik', 'yapay-zeka'],
    provinceCode: '34',
    hoursAgo: 64,
    likes: 689,
    comments: 52,
    reposts: 46,
  },
  {
    slug: 'zeynep-protokol-katki',
    author: 'zeynep.bio',
    type: 'text',
    body: 'Farklı laboratuvarlardan protokol katkısı arıyoruz. Başarısız denemeler de kabul, hatta özellikle onlar.',
    community: 'biyoteknoloji',
    topics: ['biyoteknoloji'],
    provinceCode: '34',
    hoursAgo: 86,
    likes: 203,
    comments: 16,
  },
];

export function buildPosts(now: Date): Post[] {
  return POSTS.map((input) => {
    const mediaIds = [
      ...(input.media ?? []).map(mediaId),
      ...(input.video ? [mediaId(input.video.key)] : []),
    ];

    return {
      id: postId(input.slug),
      authorId: profileId(input.author),
      type: input.type,
      body: input.body,
      visibility: 'public',
      communityId: input.community ? communityId(input.community) : null,
      topicIds: input.topics.map(topicId),
      provinceCode: input.provinceCode ?? null,
      districtCode: input.districtCode ?? null,
      projectId: input.project ? projectId(input.project) : null,
      eventId: input.event ? eventId(input.event) : null,
      whyStoryId: input.why ? whyStoryId(input.why) : null,
      resourceId: input.resource ? resourceId(input.resource) : null,
      mediaIds,
      createdAt: new Date(now.getTime() - input.hoursAgo * 3_600_000).toISOString(),
      likeCount: input.likes,
      commentCount: input.comments,
      repostCount: input.reposts ?? 0,
      isShortVideo: Boolean(input.video),
      videoKind: input.video?.kind ?? null,
    };
  });
}

export const POST_COUNT = POSTS.length;
